name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0
          pip install pandas scikit-learn numpy matplotlib joblib

      - name: Run model training
        run: |
          cd MLProject
          python modelling.py
